name: Bump Version and Build

on:
  push:
    branches:
      - main  # Runs when pushing to the `main` branch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change if using a different Java version

      - name: Bump Version
        id: version
        uses: paulhatch/semantic-version@v4
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Update `pom.xml` with New Version
        run: |
          NEW_VERSION=${{ steps.version.outputs.version }}
          xmlstarlet ed -L -N x="http://maven.apache.org/POM/4.0.0" \
            -u "/x:project/x:version" -v "$NEW_VERSION" pom.xml

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "Bump version to ${{ steps.version.outputs.version }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Create a New Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git v${{ steps.version.outputs.version }}