jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -Dspring.profiles.active=prod
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-package
          path: target/*.jar

  publish-job:
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: jar-package
          path: staging
      - run: ls -l staging/
