name: Build and Test Spring Boot Application

# Trigger the workflow on every push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17 (or your required version)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    # Step 3: Cache Maven dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the Spring Boot project
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run tests
    - name: Run Tests
      run: mvn test
